name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:webpack

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          publish_dir: dist/
          enable_jekyll: true
